//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITIndeed.PL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITIndeedEntities : DbContext
    {
        public ITIndeedEntities()
            : base("name=ITIndeedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployer> tblEmployers { get; set; }
        public virtual DbSet<tblEvent> tblEvents { get; set; }
        public virtual DbSet<tblEventShowing> tblEventShowings { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }

        public System.Data.Entity.DbSet<ITIndeed.BL.Student> Students { get; set; }

        public System.Data.Entity.DbSet<ITIndeed.BL.Employer> Employers { get; set; }
    }
}
