//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITIndeed.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployer
    {
        public System.Guid Id { get; set; }
        public string RepresentativeFirstName { get; set; }
        public string RepresentativeLastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.Guid UserId { get; set; }
        public string OrganizationName { get; set; }
        public string Industry { get; set; }
    }
}
